### ISSUE TITLE
Slides Einheitlich machen

### ISSUE THREAD

**Issue by fuerbringer** [fuerbringer/M254-Kapitel5#3]
Inhalt struktur wie bei @Hoi15A und @fuerbringer PP implementieren
Im looking at you @darjush96 @GianlucaScarciolla

**Comment by Hoi15A** [comment]
Git Gud

**Comment by fuerbringer** [comment]
``[https://github.com/fuerbringer/M254-Kapitel5/blob/master/severin/index.html](url)

**Comment by Hoi15A** [comment]
Project is over
