### ISSUE TITLE
Inhalt zu Jade konvertieren

### ISSUE THREAD

**Issue by fuerbringer** [fuerbringer/M254-Kapitel5#6]
..und die alten index.html Dateien löschen:
- [ ] delete luu/index.html @GianlucaScarciolla 
- [ ] delete darjush/index.html @darjush96 
- [x] delete severin/index.html @fuerbringer
- [x] delete austin/index.html @Hoi15A 

Und ab jetzt immer in $name/index.jade arbeiten. Notfalls README.md lesen.

**Comment by fuerbringer** [comment]
# DO IT ( ͡° ͜ʖ ͡°)

**Comment by Hoi15A** [comment]
Project is over
