### ISSUE TITLE
make inhalt.jade, + my own 10 pages

### ISSUE THREAD

**Issue by Hoi15A** [fuerbringer/M254-Kapitel5#8]
- [x] add inhalt.jade to pug components
- [x] make my own 10 pages
- [x] cry in a corner because this is boring af

**Comment by fuerbringer** [comment]
Do you seriously expect @GianlucaScarciolla and @darjush96 to finish 10 pages? :rocket: You're just issue-farming, admit it. :P

**Comment by Hoi15A** [comment]
correct, also inhalt.jade

**Comment by Hoi15A** [comment]
Shits over, finally (for now)
